### ISSUE TITLE
fullysnc jobs will queue up if a running fullsync does not finish before the next schedule starts

### ISSUE THREAD

**Issue by ashmanto** [mimiro-io/datahub#103]
If a fullsync job has a too high frequency, the next run in the schedule makes the fullsyncs queue up. 
This means that the job will go on for ever and never release. The jobs complete successfully, but it starts up again as soon as it is done.

Currently we have changed the jobs to have more space between each run (increased scheduler).

**Comment by gra-moore** [comment]
fixed.
