### ISSUE TITLE
Add support for jobs that read from one but write to many datasets

### ISSUE THREAD

**Issue by gra-moore** [mimiro-io/datahub#106]
There are several scenarios where data comes into one dataset and it is desirable to write the data of variants of it into many different datasets. While it is possible to set up jobs for each target and for that job to filter out all other data this is a lot of additional moving parts. 

Ideally it should be possible to have a single job that reads from a dataset and based on a defined criteria writes entities into the target dataset. There should be allowed a custom transform on each target. 

Initially the entity selector should be a simple definition of a property name and expected value. 

Entities that do not match any selector are dropped with no further processing. 

Batches of entities are processed as a whole. The entities in the batch are grouped based on the dataset they will be written to and then ALL entities for all datasets are committed transactionally. So either the entire original batch is committed or fails. 

It is expected that no other jobs are writing to these datasets.

**Comment by ashmanto** [comment]
https://github.com/mimiro-io/datahub/blob/master/DOCUMENTATION.md#newtransaction
solved.
