### ISSUE TITLE
Add api for updating public namespaces on a dataset

### ISSUE THREAD

**Issue by andebor** [mimiro-io/datahub#151]
Currently this can only be achieved by updating the core dataset directly.

**Comment by rompetroll** [comment]
in extention, the core dataset should ideally not be writable at all via outward APIs.

**Comment by rompetroll** [comment]
https://github.com/mimiro-io/datahub/pull/159 introduced the abitity to rename datasets by sending a PATCH payload with a new dataset name.
In the same manner, we can provide the ability to send a PATCH payload with a new set of publicNames.

**Comment by andebor** [comment]
Closing this as this is planned to be handled automatically in the future.
