### ISSUE TITLE
Support JWT verification against node security and external OAuth provider in parallel

### ISSUE THREAD

**Issue by rompetroll** [mimiro-io/datahub#265]
Currently, when datahub is set into node security mode, it can only verify its self-generated node security jwt tokens. 

It should be possible to verify more than one type of jwt token in the same datahub.

E.G. when a node security jwt token is provided with a request, datahub can verify it agains its internal node security backned, but when a jwt token from an external (configured) security service is provided, datahub should verify against that external service.

**Comment by andebor** [comment]
@rompetroll Is this implemented?
