### ISSUE TITLE
Consider adding both endpoints to read entities from dataset when dataset is specified in acls

### ISSUE THREAD

**Issue by 4hlberg** [mimiro-io/datahub#277]
Per today if you want to add both /changes and /entities to be read for a client with acls you can either 

`{ "Resource": "/datasets/some.Thing/changes", "Action": "write", "Deny": false },{ "Resource": "/datasets/some.Thing/entities", "Action": "write", "Deny": false }`

or `{ "Resource": "/datasets/some.Thing*", "Action": "write", "Deny": false }`

The second option would add access to all datasets starting with some.Thing such as some.ThingSecret

**Comment by gra-moore** [comment]
You can also just do /datasets/some.Thing/*. Is this OK? @4hlberg

**Comment by 4hlberg** [comment]
This is a good solution. I think some clarifying notes in the docs around how the grants are given on a given url would be good. I'll make a task for it and try to explain short and concise.
