### ISSUE TITLE
replace builtin json library

### ISSUE THREAD

**Issue by rompetroll** [mimiro-io/datahub#30]
We currently use golang's standard json library to marshal and unmarshal entities, but also in datahub's stream parser.
It is known that other libraries perform much better and have better memory efficiency as well. Datahub should use a better library. Some candidates:

https://github.com/minio/simdjson-go
https://github.com/ohler55/ojg
https://github.com/json-iterator/go

**Comment by ashmanto** [comment]
the goccy/go-json lib did not work as expected, we will try again with another lib.
