### ISSUE TITLE
Feature: "Smart" datasets

### ISSUE THREAD

**Issue by rompetroll** [mimiro-io/datahub#302]
The idea is building on https://github.com/mimiro-io/datahub/issues/204, but adding the possibility to provide extra parameters when fetching data from the dataset's endpoints.

A smart dataset would not store data it self, and therefore needs to be backed by another dataset (of any kind?). As such one could call it a dataset-facade, a virtual dataset, or a dataset projection as well. 

The main characteristic of a smart dataset is the ability to attach a transformation script to it. It should probably even be mandatory to provide a transformation script. The script would - like job transformations or ad hoc queries - prescribe an interface function, in which batches of the underlying dataset and the optional request parameter are injected. The script can then implement static rules and request parameter to transform the underlying dataset on the fly.

The proposed feature is also similar to https://github.com/mimiro-io/datahub/issues/196, but not quite as feature rich. The main idea is to provide a way to dynamically filter datasets - based either static transform rules, dynamic request parameters, or both.

**Comment by rompetroll** [comment]
suggested script interface:

```javascript
function transform_entities(entities, requestPayload) {
    return entities;
}
```

Given javascript's dynamic function parameter handling, this signature makes smart datasets compatible with job transform scrips, which have the signature `function transform_entities(entities) { return entities; }`.

The optional `requestPayload` does not have a predefined type/shape, it should be up to each specific smart dataset to establish a specific interface. Technically, the only requirement would be that requestPayload should be (de)serializable to a javascript-readable object across the given http->golang->goja-runtime boundaries in datahub.

`requestPayload` is optionally provided by users as body to GET requests for the given smart dataset.

A smart dataset only applies the transform script in GET requests. POSTing to a smart dataset should be rejected, possibly with an error message indicating what the underlying dataset is so that users can POST to that endpoint instead. A reason to reject POSTS is that reading from and writing to a dataset must be symmetrical: a batch that is fetched and reposted to the same dataset should be a no-op. Since the transform in smart datasets can produce vastly different outputs, this symmetry is not given.

**Comment by rompetroll** [comment]
It can also be a good idea to look at https://github.com/mimiro-io/datahub/issues/201 together with this, because storing transform scripts with a dataset is related to storing it "correctly".

**Comment by gra-moore** [comment]
@rompetroll in the function signature what do the 'entities' relate to? and should there be some config in addition to the actual transform that could get passed in. I am thinking that the transform could pull from a named dataset but rather than that be hardcoded in the transform that it could be a runtime parameter. There could be other config that the transform needs.

**Comment by rompetroll** [comment]
That is a good point, instead of being a facade in front of a specified dataset (which provides the 'entities' in the signature), this could be entirely virtual dataset, with the ability to query into one or many physical datasets as required. In that case the requirement would only be that it produces a valid UDA batch, so the signature could be.
```
function build_entities(requestPayload) {
    const entities = [];
    return entities;
}
```

One difficulty here would be support for UDA batches with continuation tokens. If we restrict the feature to be driven by one specified underlying dataset, then it is possible to just re-use the continuation tokens of the underlying dataset.

For a completely synthetic dataset, the javascript API probably would need to provide a way to work out continuation tokens in the transform code, and possibly som internal APIs to support that. e.g. a `GetEntityVersionsSince(timestamp)`
