### ISSUE TITLE
Add support for query via Javascript 

### ISSUE THREAD

**Issue by gra-moore** [mimiro-io/datahub#6]
At the moment it is possible to write and execute transforms as javascript. These transforms must be executed as part of a job or run locally with the mim CLI. 

When querying the datahub there is an API for bi-directional graph traversal that returns sets of related entities.

It will empower many use cases to allow arbitrary complex queries written in Javascript to be executed on the server and return a data table like structure as a stream. 

Proposal is to extend the transformation execution context to include a results interface that can be written to by a Javascript query. 

The queries are posted as a json payload which includes a base64 encoded string of the javascript to execute. 

Server side, the results interface should be streaming data as it receives it from the Javascript. The javascript is responsible for indicating the table columns and their type via the results interface.

**Comment by ashmanto** [comment]
Already supported with MIM CLI - the cli can run remote queries.
