### ISSUE TITLE
Expose dataset for result entities in query result

### ISSUE THREAD

**Issue by andebor** [mimiro-io/datahub#63]
I'd like the query results to show the dataset the result entities are stored in. Both for the matching entity and for the inverse matches. This could then be used to filter the results i.e. when looking for inverse matches in or more particular datasets.

**Comment by gra-moore** [comment]
Proposal for this is to introduce a new query parameter which is _merge_ default value is true. This can be set to false to get back more than one entity per URI. The dataset can also be included as part of the entity using a well known property class.

**Comment by gra-moore** [comment]
Having looked at the code this is a bit of change given the way its written at the moment.

**Comment by gra-moore** [comment]
Plan is to add a queryflag NoPartialMerge which is false by default. Setting to true changes the existing behaviour to return an Entity that has a property called partials, whose value is an array of entities. Each entity has had an additional property added that is the name of the dataset it originates from.
