### ISSUE TITLE
Add support for different login providers for datalayer access

### ISSUE THREAD

**Issue by gilgamesjh** [mimiro-io/datahub#65]
As we move to support more datalayers, and also datalayers that are configured with different security mechanisms, we need a new API to allow to add login providers.

Today there is a single login provider that supports jwt (Auth0 compatible) Bearer tokens. It also only supports a single configuration via ENV variables.

This issue suggests that we expand the internal provider map with configurations loaded through a new api.

To support full cli access the following should be implemented:

* POST /login/providers -> create a new provider
* POST /login/provider/:providerName -> update an existing provider
* GET /login/providers -> Lists all providers
* GET /login/provider/:providerName -> returns details for a provider
* DELETE /login/provider/:providerName -> deletes a provider with no jobs using it

As a start I would suggest to add 2 types of providers:
1. Jwt -> This is basically what we have to day and requires compatibility with Auth0
2. Basic -> User/Password combination

Since these contains secrets, we need to support reading from env or from a secrets store (ssm is the only supported one at the moment), but we should also allow plain text. A GET request to show a provider should then return the scrambled values if text.

An example on how to configure this is:
```json
{
    "password": {
        "type": "text",
        "value": "super-secret"
    }
}
```

An example on a (plain) provider could then end up looking like this:
```json
{
    "name":"my-plain-login",
    "type": "basic",
    "user": {
        "type": "text",
        "value": "test@testesen.no"
    },
    "password": {
        "type": "text",
        "value": "super-secret"
    }
}
```

In a job, the name "my-plain-login" can be referenced, and the http client will be decorated with the correct login mechanism.

When the type is env or ssm, the value needs to be loaded from the target location, and kept in memory while the server is 
running.

**Comment by gra-moore** [comment]
done.
